### ISSUE TITLE
ghcr.io/inlets/inlets:3.0.1 no longer pullable

### ISSUE THREAD

**Issue by michal-kazmierczak** [banzaicloud/kurun#25]
**Describe the bug**
When running the `kurun port-forward ...` command the following error is returned:
```
error: timed out waiting for the condition on deployments/app-kurun
Error: exit status 1
```

It turns out that the root cause is that `ghcr.io/inlets/inlets:3.0.1` became unavailable.

```
❯ docker pull ghcr.io/inlets/inlets:3.0.1
Error response from daemon: Head https://ghcr.io/v2/inlets/inlets/manifests/3.0.1: unauthorized
```

**Comment by bonifaido** [comment]
I just found out that inlets became a proprietary product. I'm not sure how to continue from this point. We probably should drop inlets from the port-forwarding and replace it with something else.

https://github.com/inlets/inlets-archived/commit/ae9a0f82a8914c12b338f5c310e3fcf9750e0309
