### ISSUE TITLE
Installing with Homebrew is broken

### ISSUE THREAD

**Issue by akijakya** [banzaicloud/kurun#30]
**Describe the bug**

There is a disabled dependency `inlets` that prevents installing kurun via Homebrew.

**Steps to reproduce the issue:**

```
brew install banzaicloud/tap/kurun
Error: inlets has been disabled because it has a removed upstream repository!
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bonifaido** [comment]
just fixed it in https://github.com/banzaicloud/homebrew-tap/commit/fe91658b596f5867f7ad36616b19cfcc2f23c502
