### ISSUE TITLE
Add a TLS option to inlets?

### ISSUE THREAD

**Issue by alexellis** [banzaicloud/kurun#9]
How about adding a TLS option to inlets so that you don't have to add ghost tunnel as an extra layer?

It should be relatively straight-forward to listen on a different port, given that you've already mounted the cert as a volume.

Btw inlets has also moved to https://github.com/inlets/inlets and grew a small family:

https://github.com/inlets/inlets-operator - automate inlets client/server for any Service LoadBalancer in K8s
https://github.com/inlets/inletsctl - create exit nodes on public Iaas and `inletsctl kfwd`

**Comment by bonifaido** [comment]
Once Inletes will get the TLS option we will remove Ghostunnel for sure.

Thanks for the heads up, I will check with the latest inlets now!

**Comment by alexellis** [comment]
How about sending a PR to the project from your side? 

You'd just have something like? `--tls-cert /var/cert.crt` `--tls-key /var/cert.key` ?
